#!/bin/bash
# ucloud-init 설치
# - for Ubuntu
# - x86_32 / x_86
# - 10.04 / 12.04
# Code by Jioh L. Jung (zio.zzang@gkt.com)

DEBIAN_FLAG=`cat /etc/issue.net | grep -i debian | wc -l`

# 필요한 부분 업그레이드. 업데이트+업그레이드가 되지 않으면 패키지 설치가 불가능해지는 경우가 있습니다.

apt-get update -fy
#apt-get upgrade -fy

apt-get install -fy ruby rubygems rake curl
#apt-get install -fy xe-guest-utilities


cd ~
# gem 파일을 받아옴. (개인 리포에 미러링해둠)
wget http://github.com/ziozzang/ucloud-init/raw/master/ucloud-init-0.0.1.gem
gem install ucloud-init-*.gem -n /usr/bin

ucloud-init --make-as-first-boot
rm -rf /root/.vim*
rm -f /root/*
rm -f /tmp/*
rm -f /var/log/*
rm -f /var/log/news/*
rm -f /var/log/upstart/*


# For Debian.

cat > /etc/rc.ucloud-init << EOF
#!/bin/sh

if [ "" != "\`cat /etc/issue.net | grep -i debian | awk '{print \$1}'\`" ]
then
  # for Debian
  IP=\`cat /var/lib/dhcp/dhclient.eth0.leases | grep dhcp-server-identifier | tail -1 |awk '{print \$3}'| sed -e 's/\\(.*\\);/\\1/'\`
elif [ "" != "\`cat /etc/*-release | grep -i Ubuntu\`" ]
then
  # Ubuntu
  IP=\`cat /var/lib/dhcp3/dhclient.eth0.leases | grep dhcp-server-identifier | tail -1 |awk '{print \$3}'| sed -e 's/\\(.*\\);/\\1/'\`
elif [ "" != "\`cat /etc/*-release | grep -i Cent\`" ]
then
  # Centos
  IP=\`cat /var/lib/dhclient/dhclient-eth0.leases | grep dhcp-server-identifier | tail -1 | awk '{print \$3}' | sed -e 's/\\(.*\\);/\\1/'\`
elif [ "" != "\`cat /etc/*-release | grep -i Fedora\`" ]
then
  # Fedora
  IP=\`cat /var/lib/dhclient/dhclient-eth0.leases | grep dhcp-server-identifier | tail -1 | awk '{print \$3}' | sed -e 's/\\(.*\\);/\\1/'\`
else
  echo "ucoud-init does not support this OS"
  exit 1
fi

PATH=\$PATH:/usr/local/bin

URL="http://\${IP}/latest/user-data"
USER_DATA="/root/userdata.yml"
curl \$URL > \$USER_DATA

cat \$USER_DATA | ucloud-init --pre-config-commands
cat \$USER_DATA | ucloud-init --config-commands
cat \$USER_DATA | ucloud-init --post-config-commands
EOF

chmod +x  /etc/rc.ucloud-init
if [[ ! "$(grep '^/etc/rc.ucloud-init' /etc/rc.local)" ]]; then
  sed -i -e "s,\(^exit .*\),/etc/rc.ucloud-init\n\1," /etc/rc.local
fi
