#!/bin/bash
# ucloud-init 설치
# - for Ubuntu
# - x86_32 / x_86
# - 10.04 / 12.04
# Code by Jioh L. Jung (zio.zzang@gkt.com)

DEBIAN_FLAG=`cat /etc/issue.net | grep -i debian | wc -l`
UBUNTU_FLAG=`cat /etc/issue.net | grep -i ubuntu | wc -l`

if [[ "${UBUNTU_FLAG}" -eq "1" ]]; then
  UBUNTU_VERSION=`cat /etc/lsb-release | grep "DISTRIB_RELEASE" | awk '{split($0,a,"="); print a[2]}'`
fi

# 환경을 체크하여 디렉토리를 결정 합니다
DHCP_HOOK_DIR="/etc/dhcp"
if [[ ! -d "${DHCP_HOOK_DIR}/dhclient-exit-hooks.d" ]]; then
  DHCP_HOOK_DIR="/etc/dhcp3"
fi

# 원래 미러가 느리기 때문에 미러 주소를 다음쪽으로 잠시 변경 합니다
if [[ "${UBUNTU_FLAG}" -eq "1" ]]; then
  sed -i -e "s,kr\.archive\.ubuntu\.com,ftp\.daum\.net,g" /etc/apt/sources.list
fi
# 필요한 부분 업그레이드. 업데이트+업그레이드가 되지 않으면 패키지 설치가 불가능해지는 경우가 있습니다.

apt-get update -fy
if [[ "${UBUNTU_FLAG}" -eq "1" ]]; then
  apt-get upgrade -fy
fi

apt-get install -fy ruby rubygems rake curl
if [[ "${UBUNTU_FLAG}" -eq "1" ]]; then
  apt-get install -fy xe-guest-utilities
fi

#10.4의 경우에는 다음의 패키지를 설치 해야 함.
if [[ "${UBUNTU_FLAG}" -eq "1" ]]; then
  if [[ "${UBUNTU_VERSION}" == "10.04" ]]; then
    echo "Ubuntu Lucid/10.04"
    #libopenssl-ruby1.8
  else
    echo "Ubuntu Precise/12.04"
  fi
fi
# 원래의 미러로 돌립니다.
if [[ "${UBUNTU_FLAG}" -eq "1" ]]; then
  sed -i -e "s,ftp\.daum\.net,kr\.archive\.ubuntu\.com,g" /etc/apt/sources.list
fi

cd ~
# gem 파일을 받아옴. (개인 리포에 미러링해둠)
wget http://github.com/ziozzang/ucloud-init/raw/master/ucloud-init-0.0.1.gem
gem install ucloud-init-*.gem -n /usr/bin

ucloud-init --make-as-first-boot
rm -rf /root/.vim*
rm -f /root/*
rm -f /tmp/*
rm -f /var/log/*
rm -f /var/log/news/*
rm -f /var/log/upstart/*

# For Debugging Purpose.
#sed -i -e "s,^\(RUN\).*,\1=\"no\",g" ${DHCP_HOOK_DIR}/dhclient-exit-hooks.d/debug
#sed -i -e "s,^\(RUN\).*,\1=\"no\",g" ${DHCP_HOOK_DIR}/dhclient-enter-hooks.d/debug

if [[ "${UBUNTU_FLAG}" -eq "1" ]]; then
# For Ubuntu
cat << EOF > ${DHCP_HOOK_DIR}/dhclient-exit-hooks.d/ucloud-init
# ucloud-init
# Code by Jioh L. Jung (zio.zzang@kt.com)

if [ "\${reason}" = "BOUND" ]; then
  URL="http://\${new_dhcp_server_identifier}/latest/user-data"
  USER_DATA="/root/userdata.yml"
  curl \$URL > \$USER_DATA

  cat \$USER_DATA | /usr/bin/ucloud-init --pre-config-commands
  cat \$USER_DATA | /usr/bin/ucloud-init --config-commands
  cat \$USER_DATA | /usr/bin/ucloud-init --post-config-commands
fi
EOF

/usr/bin/ucloud-init --make-as-first-boot

cat << EOF > /etc/rc0.d/S38veryinit
#!/bin/bash

rm -f /tmp/*
rm -f /var/log/*
rm -f /root/.vi*
rm -f /root/*
rm -f /var/log/news/*
rm -f /var/log/upstart/*

ucloud-init --make-as-first-boot

rm -f /etc/rc0.d/S38veryinit
EOF
chmod 777 /etc/rc0.d/S38veryinit
else
# For Debian.

cat > /etc/rc.ucloud-init << EOF
#!/bin/sh

if [ "" != "\`cat /etc/issue.net | grep -i debian | awk '{print \$1}'`" ]
then
  # for Debian
  IP=\`cat /var/lib/dhcp/dhclient.eth0.leases | grep dhcp-server-identifier | tail -1 |awk '{print \$3}'| sed -e 's/\\(.*\\);/\\1/'\`
elif [ "" != "\`cat /etc/*-release | grep -i Ubuntu\`" ]
then
  # Ubuntu
  IP=\`cat /var/lib/dhcp3/dhclient.eth0.leases | grep dhcp-server-identifier | tail -1 |awk '{print \$3}'| sed -e 's/\\(.*\\);/\\1/'\`
elif [ "" != "\`cat /etc/*-release | grep -i Cent\`" ]
then
  # Centos
  IP=\`cat /var/lib/dhclient/dhclient-eth0.leases | grep dhcp-server-identifier | tail -1 | awk '{print \$3}' | sed -e 's/\\(.*\\);/\\1/'\`
elif [ "" != "\`cat /etc/*-release | grep -i Fedora\`" ]
then
  # Fedora
  IP=\`cat /var/lib/dhclient/dhclient-eth0.leases | grep dhcp-server-identifier | tail -1 | awk '{print \$3}' | sed -e 's/\\(.*\\);/\\1/'\`
else
  echo "ucoud-init does not support this OS"
  exit 1
fi

PATH=\$PATH:/usr/local/bin

URL="http://\${IP}/latest/user-data"
USER_DATA="/root/userdata.yml"
curl \$URL > \$USER_DATA

cat \$USER_DATA | ucloud-init --pre-config-commands
cat \$USER_DATA | ucloud-init --config-commands
cat \$USER_DATA | ucloud-init --post-config-commands
EOF

chmod +x  /etc/rc.ucloud-init
if [[ ! "$(grep '^/etc/rc.ucloud-init' /etc/rc.local)" ]]; then
  sed -i -e "s,\(^exit .*\),/etc/rc.ucloud-init\n\1," /etc/rc.local
fi

fi
